[![img/pythonista.png](img/pythonista.png)](https://www.pythonista.io)

# Cliente de la *API REST*.

Esta notebook contiene celdas de código que utilizarán en el endpoint defindo en ```http:\\localhost:8000\api\<clave>``` las siguientes funciones:

* ```requests.get()```.
* ```requests.post()```.
* ```requests.delete()```.

* La siguiente celda importará el módulo ```requests```.

In [1]:
import requests

 * La siguiente celda se conectará a la URL ```"http://localhost:8000/api/``` usando el método ```GET``` y la respuesta del servidor *Django* será guardada en el objeto con nombre ```respuesta```.

In [3]:
respuesta = requests.get("http://localhost:8000/api/")

In [4]:
respuesta.status_code

200

In [5]:
respuesta.json()

{'respuesta': [{'numero_de_cuenta': 1221,
   'nombre': 'Pedro',
   'primer_apellido': 'Solis',
   'segundo_apellido': 'Cabañas',
   'carrera': 'Arquitectura',
   'semestre': 3,
   'promedio': 7.8,
   'al_corriente': False},
  {'numero_de_cuenta': 1222,
   'nombre': 'Yolanda',
   'primer_apellido': 'Jiménez',
   'segundo_apellido': 'Lerdo',
   'carrera': 'Actuaría',
   'semestre': 3,
   'promedio': 6.0,
   'al_corriente': False},
  {'numero_de_cuenta': 1223,
   'nombre': 'Juan',
   'primer_apellido': 'Ramos',
   'segundo_apellido': 'Breña',
   'carrera': 'Sistemas',
   'semestre': 9,
   'promedio': 8.6,
   'al_corriente': True},
  {'numero_de_cuenta': 1224,
   'nombre': 'Mayra Jimena',
   'primer_apellido': 'Cervantes',
   'segundo_apellido': 'Lisama',
   'carrera': 'Derecho',
   'semestre': 12,
   'promedio': 9.2,
   'al_corriente': True}]}

 * La siguiente celda se conectará a la URL ```"http://localhost:8000/api/1223``` usando el método ```GET``` y la respuesta del servidor *Django* será guardada en el objeto con nombre ```respuesta```.

In [6]:
respuesta = requests.get("http://localhost:8000/api/1223")

* En este casó existe en la base de datos un alumno con número de cuenta ```1223```, por lo que el servidor *Django* regresará los datos de dicho alumno.

In [7]:
respuesta.status_code

200

In [8]:
respuesta.json()

{'numero_de_cuenta': 1223,
 'nombre': 'Juan',
 'primer_apellido': 'Ramos',
 'segundo_apellido': 'Breña',
 'carrera': 'Sistemas',
 'semestre': 9,
 'promedio': 8.6,
 'al_corriente': True}

 * La siguiente celda se conectará a la URL ```"http://localhost:8000/api/3000``` usando el método ```GET``` y la respuesta del servidor *Django* será guardada en el objeto con nombre ```respuesta```.

In [9]:
respuesta = requests.get("http://localhost:8000/api/3000")

* La base de datos de la aplicación no contiene un objeto con ese número de cuenta.

In [11]:
respuesta.status_code

404

In [12]:
respuesta.content

b''

* La siguiente celda creará un objeto de tipo ```dict``` que contiene una estructrua de datos compatible con el modelo ```Alumno```.

In [5]:
datos ={'nombre':'Juan', 'primer_apellido': 'Escutia', 'segundo_apellido':'Aventado', 
        'carrera':'Arquitectura', 'semestre':1, 'promedio':10, 'al_corriente':True,}

In [6]:
respuesta = requests.post("http://localhost:8000/api/1221", data=datos)

In [7]:
respuesta.status_code

400

In [16]:
respuesta.json()

{'nombre': 'Juan',
 'primer_apellido': 'Escutia',
 'segundo_apellido': 'Aventado',
 'carrera': 'Arquitectura',
 'semestre': '1',
 'promedio': '10',
 'al_corriente': 'True',
 'numero_de_cuenta': '1229'}

* La siguiente celda enviará nuevamente los datos a la URL ```http://localhost:8000/api/1229```.

In [17]:
respuesta = requests.post("http://localhost:8000/api/1229", data=datos)

* Debido a que ya existe un objeto con la clave ```1229```, ap respuesta es un estado ```400```.

In [18]:
respuesta.status_code

400

In [37]:
datos ={'nombre':'Agustín',
        'carrera':'Actuaría', 'semestre':1, 'promedio':10, 'al_corriente':True,}

In [38]:
respuesta = requests.post("http://localhost:8000/api/1230", data=datos)

In [39]:
respuesta.status_code

400

* La siguiente celda accederá a la URL ```http://localhost:8000/api/1225``` con el método ```DELETE```.

In [40]:
respuesta = requests.delete("http://localhost:8000/api/1225")

In [41]:
respuesta.status_code

200

In [42]:
respuesta.json()

{'estado': 'eliminado'}

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2019.</p>